name: Continuous Integration (CI)
# Run the workflow each time code is pushed, or when a pull-request is created
on: [push, pull_request]

jobs:
  # Build the app
  build:
    # Configure the job
    name: Build
    runs-on: ubuntu-latest
    # Steps to run
    steps:
      - run: echo "Build the app..."
      - run: echo "Not implemented to save time when running the workflow"

  # Run security scans
  scan:
    # Configure the job
    name: Run security scans
    needs: build
    runs-on: ubuntu-latest

    # Steps to run
    steps:
      # DevSkim
      # - Some CI support inbuilt tasks and scans, for  ease of use
      # - We could install and run DevSkim directly, but we can do it more easily using the DevSkim action
      # - See docs at: https://github.com/microsoft/DevSkim-Action
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "3.1.x"
      - run: dotnet tool install --global Microsoft.CST.DevSkim.CLI
      - run: devskim analyze . result.txt
      # Publish the scan results as an artifact
      - uses: actions/upload-artifact@v2
        with:
          name: scan-results
          path: result.txt

  # Deploy the app
    # Configure the job
  deploy:
    name: Deploy
    needs: scan
    runs-on: ubuntu-latest

    # Steps to run
    steps:
      - run: echo "Deploy the app..."
      - run: echo "Not implemented to save time when running the workflow"
