name: Continuous Integration (CI)
# Run the workflow each time code is pushed, or when a pull-request is created
on: [push, pull_request]

jobs:
  # Build the app
  build:
    # Configure the job
    name: Build
    runs-on: ubuntu-latest
    # Steps to run
    steps:
      - run: echo "Build the app..."
      - run: echo "Not implemented to save time when running the workflow"

  # Run security scans
  scan:
    # Configure the job
    name: Run security scans
    needs: build
    runs-on: ubuntu-latest

    # Steps to run
    steps:
      # Owasp dependency check
      name: Checkout
        uses: actions/checkout@v2
      - name: Build project with Maven
        run: mvn clean install
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports

      # DevSkim
      # - Some CI support inbuilt tasks and scans, for  ease of use
      # - We could install and run DevSkim directly, but we can do it more easily using the DevSkim action
      # - See docs at: https://github.com/microsoft/DevSkim-Action
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "3.1.x"
      - run: dotnet tool install --global Microsoft.CST.DevSkim.CLI
      - run: devskim analyze . result.txt
      # Publish the scan results as an artifact
      - uses: actions/upload-artifact@v2
        with:
          name: scan-results
          path: result.txt

  # Deploy the app
  deploy:
    # Configure the job
    name: Deploy
    needs: scan
    runs-on: ubuntu-latest

    # Steps to run
    steps:
      - run: echo "Deploy the app..."
      - run: echo "Not implemented to save time when running the workflow"
